### ISSUE TITLE
Move to separate repo?

### ISSUE THREAD

**Issue by 13rac1** [AngelAlvarado/dockerizing-streamsets-tutorials#3]
You've moved beyond the `kafkaplugin` being a simple tutorial extension.

`AngelAlvarado/docker-minecraft-kafka-streamsets` ?

**Comment by AngelAlvarado** [comment]
You are right @eosrei, thanks for the suggestion and thanks for taking a look at this branch's code. Gonna move it to its own [repo](https://github.com/AngelAlvarado/docker-streamsets-kafka-minecraft).
